language: python
env:
  - AWS_DEFAULT_REGION="ap-southeast-2"
python:
  - "2.7"
install:
  - "pip install coveralls"
  - "pip install -r requirements.txt"
script: "coverage run --source acmagent setup.py test"
after_success:
  - "coveralls"
